steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/sv2-vue:$COMMIT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/sv2-vue:$BRANCH_NAME',
    '-f', 'Dockerfile.prod',
    '--build-arg', 'environment=${_ENVIRONMENT}',
    '.',
  ]
  env:
  - 'DOCKER_BUILDKIT=1'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/sv2-vue', '--all-tags' ]
- name: 'gcr.io/$PROJECT_ID/helm'
  args: [
    'upgrade',
    '--install',
    '-f', '/workspace/helm/values/${_ENVIRONMENT}.yaml',
    '--set', 'version=$COMMIT_SHA',
    '-n', '${_ENVIRONMENT}',
    'sv2-vue',
    '/workspace/helm'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=us-1'
timeout: 1800s
substitutions:
  _ENVIRONMENT: staging
