FROM node:16-alpine as build-stage
ARG environment

WORKDIR /app
COPY package*.json ./
RUN apk add python3 make g++
RUN yarn install
COPY ./ .

ENV NODE_ENV=production
RUN yarn build -- --mode ${environment}

FROM gcr.io/sellervue/nginx:1.19.8-alpine as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
